#!/usr/bin/perl

foreach my $line (<STDIN>) {
	my $origin = "emergingthreads:".time;
	next if ($line =~ /^\s*\#.*$/ || $line =~ /^\s*$/); # skip empty and comment lines

	my ($ip_list) = $line=~m/alert ip \$HOME_NET any \-\> \[([^\]]+)\]/;
	foreach my $ip (split(/,/,$ip_list)) {
		print join('|',$ip, "", "", $origin)."\n";
	}
}
