#!/usr/bin/perl

sub get_version ($) {
	my ($filename) = @_;
	return `stat -t $filename | cut -f 13 -d" "`;
}

$filename = $ARGV[0];

my ($stamp) = get_version($filename);
chomp($stamp);

# c&c's are timed out one week after the lists age. This means that we don't accept c&c's from a list that is older than a week
my $expire = $stamp + 86400*7; 

open(BOTNETS, "<$filename");

foreach my $line (<BOTNETS>) {
	next if ($line =~ /^\s*\#.*$/ || $line =~ /^\s*$/); # skip empty and comment lines

	my ($ip_list) = $line=~m/alert ip \$HOME_NET any \-\> \[([^\]]+)\]/;
	foreach my $ip (split(/,/,$ip_list)) {
		print join('|',$ip, "", "", "emergingthreads", $stamp, $expire, "")."\n";
	}
}
